# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/barcode_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_barcodeDialog(object):
    def setupUi(self, barcodeDialog):
        barcodeDialog.setObjectName("barcodeDialog")
        barcodeDialog.resize(400, 300)
        barcodeDialog.setMaximumSize(QtCore.QSize(400, 300))
        barcodeDialog.setSizeGripEnabled(False)
        barcodeDialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(barcodeDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.comboBox = QtWidgets.QComboBox(barcodeDialog)
        self.comboBox.setGeometry(QtCore.QRect(110, 20, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(barcodeDialog)
        self.label.setGeometry(QtCore.QRect(50, 20, 51, 21))
        self.label.setObjectName("label")
        self.checkBox = QtWidgets.QCheckBox(barcodeDialog)
        self.checkBox.setGeometry(QtCore.QRect(230, 20, 70, 17))
        self.checkBox.setObjectName("checkBox")
        self.lineEdit = QtWidgets.QLineEdit(barcodeDialog)
        self.lineEdit.setGeometry(QtCore.QRect(110, 70, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(barcodeDialog)
        self.label_2.setGeometry(QtCore.QRect(80, 70, 21, 21))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(barcodeDialog)
        self.buttonBox.accepted.connect(barcodeDialog.accept)
        self.buttonBox.rejected.connect(barcodeDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(barcodeDialog)

    def retranslateUi(self, barcodeDialog):
        _translate = QtCore.QCoreApplication.translate
        barcodeDialog.setWindowTitle(_translate("barcodeDialog", "Barcode Options"))
        self.comboBox.setItemText(0, _translate("barcodeDialog", "Code 39"))
        self.comboBox.setItemText(1, _translate("barcodeDialog", "Code 128"))
        self.label.setText(_translate("barcodeDialog", "Symbology"))
        self.checkBox.setText(_translate("barcodeDialog", "Checksum"))
        self.label_2.setText(_translate("barcodeDialog", "Text"))
