# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/image_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_imageDialog(object):
    def setupUi(self, imageDialog):
        imageDialog.setObjectName("imageDialog")
        imageDialog.resize(400, 300)
        imageDialog.setMaximumSize(QtCore.QSize(400, 300))
        imageDialog.setSizeGripEnabled(False)
        imageDialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(imageDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(imageDialog)
        self.buttonBox.accepted.connect(imageDialog.accept)
        self.buttonBox.rejected.connect(imageDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(imageDialog)

    def retranslateUi(self, imageDialog):
        _translate = QtCore.QCoreApplication.translate
        imageDialog.setWindowTitle(_translate("imageDialog", "Image Options"))
