# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/table_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tableDialog(object):
    def setupUi(self, tableDialog):
        tableDialog.setObjectName("tableDialog")
        tableDialog.resize(400, 290)
        tableDialog.setMaximumSize(QtCore.QSize(400, 300))
        tableDialog.setSizeGripEnabled(False)
        tableDialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(tableDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(tableDialog)
        self.buttonBox.accepted.connect(tableDialog.accept)
        self.buttonBox.rejected.connect(tableDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(tableDialog)

    def retranslateUi(self, tableDialog):
        _translate = QtCore.QCoreApplication.translate
        tableDialog.setWindowTitle(_translate("tableDialog", "Table Options"))
