# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/text_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_textDialog(object):
    def setupUi(self, textDialog):
        textDialog.setObjectName("textDialog")
        textDialog.resize(400, 300)
        textDialog.setMaximumSize(QtCore.QSize(400, 300))
        textDialog.setSizeGripEnabled(False)
        textDialog.setModal(False)
        self.buttonBox = QtWidgets.QDialogButtonBox(textDialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(textDialog)
        self.buttonBox.accepted.connect(textDialog.accept)
        self.buttonBox.rejected.connect(textDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(textDialog)

    def retranslateUi(self, textDialog):
        _translate = QtCore.QCoreApplication.translate
        textDialog.setWindowTitle(_translate("textDialog", "Text Options"))
